/*CRIAÇÃO DE TABELAS*/
CREATE TABLE dogs
(
  id   INTEGER NOT NULL PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE cats
(
  id   INTEGER NOT NULL PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);  

/*CARGA DE DADOS*/
BEGIN
  INSERT INTO dogs(ID,NAME)VALUES(1,'Totó');
  INSERT INTO dogs(ID,NAME)VALUES(2,'Neguinho');
  INSERT INTO dogs(ID,NAME)VALUES(3,'Ozzy');
  INSERT INTO dogs(ID,NAME)VALUES(4,'Meg');
  INSERT INTO dogs(ID,NAME)VALUES(5,'Lulu');
  COMMIT;
EXCEPTION
  WHEN OTHERS
    THEN RAISE_APPLICATION_ERROR(-20001, 'ERRO AO ATUALIZAR A TABELA: dogs - ' || SQLCODE || SQLERRM);
    ROLLBACK;
END;

BEGIN
  INSERT INTO cats(ID,NAME)VALUES(1,'Bichano');
  INSERT INTO cats(ID,NAME)VALUES(2,'Miau');
  INSERT INTO cats(ID,NAME)VALUES(3,'Magoo');
  INSERT INTO cats(ID,NAME)VALUES(4,'Ragnar');
  INSERT INTO cats(ID,NAME)VALUES(5,'Loki');
  COMMIT;
EXCEPTION
  WHEN OTHERS
    THEN RAISE_APPLICATION_ERROR(-20001, 'ERRO AO ATUALIZAR A TABELA: cats - ' || SQLCODE || SQLERRM);
    ROLLBACK;
END;
